name: Unit Test Execution

on:
  pull_request:
     branches: [ main ]

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Ionic Test web app
        run: |
          cd ./app
          npm install
          npm run test -- --no-watch --no-progress
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "./app/test-results/*.xml"
      
      - name: Comment Test Coverage
        uses: AthleticNet/comment-test-coverage@1.1
        if: always()
        with:
          token: ${{ github.token }}
          path: ./app/test-results/coverage-summary.json
          title: Karma Test Coverage